
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KommunikationService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9090/ws?wsdl")
public class KommunikationService
    extends Service
{

    private final static URL KOMMUNIKATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException KOMMUNIKATIONSERVICE_EXCEPTION;
    private final static QName KOMMUNIKATIONSERVICE_QNAME = new QName("http://ws/", "KommunikationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KOMMUNIKATIONSERVICE_WSDL_LOCATION = url;
        KOMMUNIKATIONSERVICE_EXCEPTION = e;
    }

    public KommunikationService() {
        super(__getWsdlLocation(), KOMMUNIKATIONSERVICE_QNAME);
    }

    public KommunikationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KOMMUNIKATIONSERVICE_QNAME, features);
    }

    public KommunikationService(URL wsdlLocation) {
        super(wsdlLocation, KOMMUNIKATIONSERVICE_QNAME);
    }

    public KommunikationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KOMMUNIKATIONSERVICE_QNAME, features);
    }

    public KommunikationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KommunikationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Kommunikation
     */
    @WebEndpoint(name = "KommunikationPort")
    public Kommunikation getKommunikationPort() {
        return super.getPort(new QName("http://ws/", "KommunikationPort"), Kommunikation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Kommunikation
     */
    @WebEndpoint(name = "KommunikationPort")
    public Kommunikation getKommunikationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "KommunikationPort"), Kommunikation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KOMMUNIKATIONSERVICE_EXCEPTION!= null) {
            throw KOMMUNIKATIONSERVICE_EXCEPTION;
        }
        return KOMMUNIKATIONSERVICE_WSDL_LOCATION;
    }

}
