
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "KommunikationService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9090/ws?wsdl")
public class KommunikationService extends Service {

	private final static URL KOMMUNIKATIONSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(ws.KommunikationService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = ws.KommunikationService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:9090/ws?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:9090/ws?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		KOMMUNIKATIONSERVICE_WSDL_LOCATION = url;
	}

	public KommunikationService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public KommunikationService() {
		super(KOMMUNIKATIONSERVICE_WSDL_LOCATION, new QName("http://ws/", "KommunikationService"));
	}

	/**
	 * 
	 * @return returns Kommunikation
	 */
	@WebEndpoint(name = "KommunikationPort")
	public Kommunikation getKommunikationPort() {
		return super.getPort(new QName("http://ws/", "KommunikationPort"), Kommunikation.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns Kommunikation
	 */
	@WebEndpoint(name = "KommunikationPort")
	public Kommunikation getKommunikationPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://ws/", "KommunikationPort"), Kommunikation.class, features);
	}

}
