
package de.kiltz.seminar.ejb3.ws.komplexer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DomainService", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DomainService {


    /**
     * 
     * @return
     *     returns de.kiltz.seminar.ejb3.ws.komplexer.DomainObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDomainObject", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.GetDomainObject")
    @ResponseWrapper(localName = "getDomainObjectResponse", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.GetDomainObjectResponse")
    public DomainObject getDomainObject();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDomainObject", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.SetDomainObject")
    @ResponseWrapper(localName = "setDomainObjectResponse", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.SetDomainObjectResponse")
    public void setDomainObject(
        @WebParam(name = "arg0", targetNamespace = "")
        DomainObject arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns de.kiltz.seminar.ejb3.ws.komplexer.DomainObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setUndGetDomainObject", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.SetUndGetDomainObject")
    @ResponseWrapper(localName = "setUndGetDomainObjectResponse", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", className = "de.kiltz.seminar.ejb3.ws.komplexer.SetUndGetDomainObjectResponse")
    public DomainObject setUndGetDomainObject(
        @WebParam(name = "arg0", targetNamespace = "")
        DomainObject arg0);

}
