
package de.kiltz.seminar.ejb3.ws.komplexer;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DomainServiceImplService", targetNamespace = "http://komplexer.ws.ejb3.seminar.kiltz.de/", wsdlLocation = "http://127.0.0.1:8080/EJB3WebService/DomainServiceImpl?wsdl")
public class DomainServiceImplService
    extends Service
{

    private final static URL DOMAINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.kiltz.seminar.ejb3.ws.komplexer.DomainServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.kiltz.seminar.ejb3.ws.komplexer.DomainServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/EJB3WebService/DomainServiceImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/EJB3WebService/DomainServiceImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOMAINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DomainServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainServiceImplService() {
        super(DOMAINSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://komplexer.ws.ejb3.seminar.kiltz.de/", "DomainServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DomainService
     */
    @WebEndpoint(name = "DomainServiceImplPort")
    public DomainService getDomainServiceImplPort() {
        return super.getPort(new QName("http://komplexer.ws.ejb3.seminar.kiltz.de/", "DomainServiceImplPort"), DomainService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainService
     */
    @WebEndpoint(name = "DomainServiceImplPort")
    public DomainService getDomainServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://komplexer.ws.ejb3.seminar.kiltz.de/", "DomainServiceImplPort"), DomainService.class, features);
    }

}
