<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://ws/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws/"
	name="Kommunikation">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://ws/" schemaLocation="daten.xsd" />
		</xsd:schema>
	</types>
	<message name="ping">
		<part name="parameters" element="tns:ping" />
	</message>
	<message name="pingResponse">
		<part name="parameters" element="tns:pingResponse" />
	</message>
	<portType name="Kommunikation">
		<operation name="ping">
			<input message="tns:ping" />
			<output message="tns:pingResponse" />
		</operation>
	</portType>
	<binding name="KommunikationPortBinding" type="tns:Kommunikation">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="ping">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="Kommunikation">
		<port name="KommunikationPort" binding="tns:KommunikationPortBinding">
			<soap:address location="http://localhost:9090/ws" />
		</port>
	</service>
</definitions>