
package de.kiltz.kv.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KundenVerwaltungWebServiceImplService", targetNamespace = "http://ws.kv.kiltz.de/", wsdlLocation = "file:/C:/Users/Administrator/IdeaProjects/jee/kv-main/wsdl/KundenVerwaltungWebServiceImplService.wsdl")
public class KundenVerwaltungWebServiceImplService
    extends Service
{

    private final static URL KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.kv.kiltz.de/", "KundenVerwaltungWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/IdeaProjects/jee/kv-main/wsdl/KundenVerwaltungWebServiceImplService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public KundenVerwaltungWebServiceImplService() {
        super(__getWsdlLocation(), KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public KundenVerwaltungWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public KundenVerwaltungWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_QNAME);
    }

    public KundenVerwaltungWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public KundenVerwaltungWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KundenVerwaltungWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KundenVerwaltungWebService
     */
    @WebEndpoint(name = "KundenVerwaltungWebServiceImplPort")
    public KundenVerwaltungWebService getKundenVerwaltungWebServiceImplPort() {
        return super.getPort(new QName("http://ws.kv.kiltz.de/", "KundenVerwaltungWebServiceImplPort"), KundenVerwaltungWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KundenVerwaltungWebService
     */
    @WebEndpoint(name = "KundenVerwaltungWebServiceImplPort")
    public KundenVerwaltungWebService getKundenVerwaltungWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.kv.kiltz.de/", "KundenVerwaltungWebServiceImplPort"), KundenVerwaltungWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return KUNDENVERWALTUNGWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
