
package de.kiltz.kv.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "KundenWSException", targetNamespace = "http://ws.kv.kiltz.de/")
public class KundenWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KundenWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public KundenWSException_Exception(String message, KundenWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public KundenWSException_Exception(String message, KundenWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.kiltz.kv.ws.KundenWSException
     */
    public KundenWSException getFaultInfo() {
        return faultInfo;
    }

}
