
package de.kiltz.kv.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KundenVerwaltungWebService", targetNamespace = "http://ws.kv.kiltz.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KundenVerwaltungWebService {


    /**
     * 
     * @param id
     * @return
     *     returns de.kiltz.kv.ws.KundeXsd
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "holeKunde", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.HoleKunde")
    @ResponseWrapper(localName = "holeKundeResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.HoleKundeResponse")
    public KundeXsd holeKunde(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param suchBegriff
     * @return
     *     returns java.util.List<de.kiltz.kv.ws.KundeXsd>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sucheKunde", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.SucheKunde")
    @ResponseWrapper(localName = "sucheKundeResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.SucheKundeResponse")
    public List<KundeXsd> sucheKunde(
        @WebParam(name = "suchBegriff", targetNamespace = "")
        String suchBegriff);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "loescheKunde", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.LoescheKunde")
    @ResponseWrapper(localName = "loescheKundeResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.LoescheKundeResponse")
    public void loescheKunde(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param adresseXsd
     * @return
     *     returns de.kiltz.kv.ws.AdresseXsd
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "neueAdresse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.NeueAdresse")
    @ResponseWrapper(localName = "neueAdresseResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.NeueAdresseResponse")
    public AdresseXsd neueAdresse(
        @WebParam(name = "adresseXsd", targetNamespace = "")
        AdresseXsd adresseXsd);

    /**
     * 
     * @param kundeXsd
     * @return
     *     returns de.kiltz.kv.ws.KundeXsd
     * @throws KundenWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "neuerKunde", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.NeuerKunde")
    @ResponseWrapper(localName = "neuerKundeResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.NeuerKundeResponse")
    public KundeXsd neuerKunde(
        @WebParam(name = "kundeXsd", targetNamespace = "")
        KundeXsd kundeXsd)
        throws KundenWSException_Exception
    ;

    /**
     * 
     * @param kundeXsd
     * @return
     *     returns de.kiltz.kv.ws.KundeXsd
     * @throws KundenWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "aendereKunde", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.AendereKunde")
    @ResponseWrapper(localName = "aendereKundeResponse", targetNamespace = "http://ws.kv.kiltz.de/", className = "de.kiltz.kv.ws.AendereKundeResponse")
    public KundeXsd aendereKunde(
        @WebParam(name = "kundeXsd", targetNamespace = "")
        KundeXsd kundeXsd)
        throws KundenWSException_Exception
    ;

}
